Shrink unsafe block for the from_lpstr function
Traverse-Research/hassle-rs pull request #40
Opened 2022-05-03 07:35 UTC by peamaeq

2022-05-03 08:11 UTC, MarijnS95 requested changes
Thanks! You can shrink one of the blocks even further :)

Would you mind also updating the commit title to match the PR title?

2022-05-03 08:11 UTC, MarijnS95 commented on src/utils.rs
> +    let len = unsafe { (0..).take_while(|&i| *string.offset(i) != 0).count() };
You can wrap this even tighter, only `*string.offset(i)` needs to reside in an unsafe block :slightly_smiling_face:.

2022-05-03 08:11 UTC, MarijnS95 commented on src/utils.rs
> +    std::str::from_utf8(slice).map(|s| s.to_owned()).unwrap()
While at it, perhaps we should simplify this to:

```suggestion
    std::str::from_utf8(slice).unwrap().to_owned()
```

2022-05-03 11:25 UTC, peamaeq commented
> 谢谢！您可以进一步缩小其中一个块:)
> 
> 你介意更新提交标题以匹配 PR 标题吗？

Thanks for the suggestion.

2022-05-03 11:34 UTC, MarijnS95 commented
What does 0503 mean?

2022-05-03 11:44 UTC, peamaeq commented
> What does 0503 mean?
3 May😊

2022-05-03 12:15 UTC, MarijnS95 commented
Commits already have a date associated with them :)

If I may ask, why not put the pull request title in the commit title?

2022-05-03 12:16 UTC, MarijnS95 commented
And what's with from_lpstr()` specifically? There seem to be more code blocks around that could get the same treatment.

2022-05-03 13:11 UTC, peamaeq commented
> And what's with `from_lpstr()` specifically? There seem to be more code blocks around that could get the same treatment.
Yes, utils::from_bstrcan also treat the same.🙌

2023-01-13 09:18 UTC, Jasper-Bekkers approved these changes

2023-01-13 09:41 UTC, MarijnS95 approved these changes
Switching this to an approval, but it'd be nice to shrink more `unsafe` blocks while at it (if we didn't already do so in other PRs).

2025-04-15 11:56 UTC, MarijnS95 commented
We have completely refactored `from_lpstr()` and implemented the missing `unsafe` reduction in `from_bstr()` in another PR too. Thank you for your contribution, but this is no longer needed :slightly_smiling_face:

2025-04-15 11:56 UTC, closed without merging